# Generated by Django 2.1.1 on 2018-09-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_n', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['doc_n'],
            },
        ),
        migrations.CreateModel(
            name='OpisPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_n', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['opis_n'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_elem', models.BooleanField(default='True', verbose_name='on/off')),
                ('product_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='number')),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='invoice')),
                ('data_invoice', models.DateField(blank=True, null=True)),
                ('sending_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='sending')),
                ('data_sending', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('mn', 'Минск'), ('br', 'Брест'), ('gr', 'Гродно'), ('go', 'Гомель'), ('vi', 'Витебск'), ('pi', 'Пинск')], max_length=2, null=True)),
                ('doc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.DocPost')),
                ('opis_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.OpisPost')),
            ],
            options={
                'ordering': ['product_number'],
            },
        ),
        migrations.CreateModel(
            name='SerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['ser'],
            },
        ),
        migrations.CreateModel(
            name='TechPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_n', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['tech_n'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ser_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.SerPost'),
        ),
        migrations.AddField(
            model_name='post',
            name='tech_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.TechPost'),
        ),
    ]
