# Generated by Django 2.1.1 on 2018-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ser_name',
        ),
        migrations.AddField(
            model_name='post',
            name='ser_name',
            field=models.ManyToManyField(blank=True, null=True, to='post.SerPost'),
        ),
    ]
