# Generated by Django 2.1.1 on 2018-09-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180916_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ser_name',
        ),
        migrations.AddField(
            model_name='post',
            name='ser_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.SerPost'),
        ),
    ]
