# Generated by Django 2.1.1 on 2018-09-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_whom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
