# Generated by Django 2.1.1 on 2018-09-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180921_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['product_number']},
        ),
    ]
