# Generated by Django 2.1.1 on 2018-10-20 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0007_auto_20180921_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['data_invoice']},
        ),
    ]
